/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package food_masters;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.PasswordField;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author S.Saqib
 */
public class login extends javax.swing.JFrame {
Connection con= null;
// PreparedStatement ps=null;
  Statement ps=null;
    ResultSet rs=null;
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        setPreferredSize(new java.awt.Dimension(720, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 42)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Food Masters");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 30, 340, 80);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The food you deserve");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 110, 220, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\S.Saqib\\Documents\\NetBeansProjects\\pics\\changed\\i7.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 380, 480);

        jPanel1.setBackground(new java.awt.Color(104, 58, 58));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(153, 153, 255), null, new java.awt.Color(0, 0, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setText("Sign in");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 71, 36));

        jLabel4.setFont(new java.awt.Font("Chaparral Pro", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 70, -1));

        jLabel5.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Login Panel");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 29, 180, -1));

        jTextField1.setBackground(new java.awt.Color(104, 58, 58));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 230, 30));

        jLabel3.setFont(new java.awt.Font("Chaparral Pro", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 90, -1));

        jLabel7.setFont(new java.awt.Font("Chaparral Pro", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Forgot your password?");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Click here");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(104, 58, 58));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(null);
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 240, 30));

        jLabel6.setFont(new java.awt.Font("Chaparral Pro", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Don't have an account yet ?");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setText("Create Account");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jLabel9.setBackground(new java.awt.Color(104, 58, 58));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 480));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 152, 240, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 240, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(370, 0, 350, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String n=jTextField1.getText();
        String k = new String(jPasswordField1.getPassword());

        if(n.isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Name cannot be empty", "Invalid name", HEIGHT);
        }
        if(k.isEmpty())
        {
            JOptionPane.showMessageDialog(rootPane, "Please enter a valid password", "Invalid password", HEIGHT);
        }
        if(n.isEmpty()==false && k.isEmpty()==false )
        {

                                  //  String query="Select role_name from saqib.roles where role_id=select role_id from saqib.users where name='"+n+"' and password2='"+k+"'";
                                    String query="Select role_id from saqib.roles where role_id=(Select role_id from saqib.users where name='"+n+"' and password2='"+k+")'";
                                     try {
                                            con=DriverManager.getConnection("jdbc:derby://localhost:1527/foodmasters", "saqib", "saqib");
                                        } catch (SQLException ex) {
                                            JOptionPane.showMessageDialog(rootPane, "failed", "bye", HEIGHT);
                                        }
            
                              try
                              {
                
                //                      ps=con.Statement(query);
                //                      ps.setString(1, jTextField1.getText());
                //                      ps.setString(2,k);
                                      ps=con.createStatement();
                
                                      rs=ps.executeQuery(query);
                                      while(rs.next())
                                      {
                                          int t=rs.getInt("role_id");
                                          //System.out.println("\trole: " + t);
                                          if(t==1)
                                          {
                                          JOptionPane.showMessageDialog(rootPane, "Loggin successful as admin","Welcome Admin Shah G", HEIGHT);
                                          this.setVisible(false);
                                          new admin_dashboard().setVisible(true);
                                          }
                                          else if(t==2)
                                          {
                                          JOptionPane.showMessageDialog(rootPane, "Loggin successful as Restaurant admin","Welcome to Restaurant Admin panel", HEIGHT);
                                          this.setVisible(false);
                                        //  new admin_dashboard().setVisible(true);
                                          }
                                          else if(t==3)
                                          {
                                          JOptionPane.showMessageDialog(rootPane, "Loggin successful as Dealing agent","Welcome to Agent Panel", HEIGHT);
                                          this.setVisible(false);
                                         // new admin_dashboard().setVisible(true);
                                          }
                                          else if(t==4)
                                          {
                                          JOptionPane.showMessageDialog(rootPane, "Loggin successful as Delivery Boy","Welcome to Delivery Management panel", HEIGHT);
                                          this.setVisible(false);
                                          new admin_dashboard().setVisible(true);
                                          }
                                          else if(t==5)
                                          {
                                          JOptionPane.showMessageDialog(rootPane, "Loggin successful as Customer","Welcome to Customer Panel", HEIGHT);
                                          this.setVisible(false);
                                          new place_order().setVisible(true);
                                          }
                                       }
                // System.out.println(t);
                
                //                      if(rs.next())
                //                      {
                    //                      JOptionPane.showMessageDialog(rootPane, "congoz", "Login Successful", HEIGHT);
                    //                      }
                //                      else{
                    //                          JOptionPane.showMessageDialog(rootPane, "Invalid Username or password", "Login failed", HEIGHT);
                    //                      }
                                  }
                              catch(SQLException e)
                              {
                                              JOptionPane.showMessageDialog(rootPane, "No user found against given username and password", "User not found!", HEIGHT);
                                      //e.printStackTrace();
                                  }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
