/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package food_masters;

import static java.awt.image.ImageObserver.HEIGHT;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author mehbo
 */

public class restaurant extends javax.swing.JDialog {
  Connection con= null;
// PreparedStatement ps=null;
   Statement ps=null;
    ResultSet rs=null;
    /**
     * Creates new form restaurant
     */
    public restaurant(java.awt.Frame parent, boolean modal) {
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         String st1=jTextField1.getText();
         String st2=jTextField2.getText();
         String st3=jTextField3.getText();
         String pw1 = new String(jPasswordField1.getPassword());
         String pw2 = new String(jPasswordField2.getPassword());
         Customer c=new Customer();
          if(st1.isEmpty())
            {
                 JOptionPane.showMessageDialog(rootPane, "Name cannot be empty", "Invalid name", HEIGHT);
            }
          if(st2.isEmpty())
            {
                 JOptionPane.showMessageDialog(rootPane, "Please enter a valid email", "Invalid email", HEIGHT);
            }
           if(st3.isEmpty())
            {
                 JOptionPane.showMessageDialog(rootPane, "enter a phone number", "Invalid phone number", HEIGHT);
            }
            if(pw1.isEmpty())
            {
                 JOptionPane.showMessageDialog(rootPane, "Password cannot be empty", "Invalid name", HEIGHT);
            }
             if(pw2.isEmpty())
            {
                 JOptionPane.showMessageDialog(rootPane, "confirm password cannot be empty", "Invalid name", HEIGHT);
            }
              if(pw1!=null && pw2.equals(pw1)==false)
            {
                 JOptionPane.showMessageDialog(rootPane, "Passwords must be same", "Passwords do not match", HEIGHT);
            }
          if(st1.isEmpty()==false && st2.isEmpty()==false && st3.isEmpty()==false && pw1.isEmpty()==false && pw2.isEmpty()==false && pw2.equals(pw1)==true)
          { 
              test te=new test();
              boolean flag =te.isValid(st2);
              boolean flag1 =te.isValid_mobile(st3);
             if(flag==true&&flag1==true)
             {
                JOptionPane.showMessageDialog(rootPane, "ok", "bye", HEIGHT);
                c.set_user(st1,st2, st3, pw1);
             
                      try{
                           con=DriverManager.getConnection("jdbc:derby://localhost:1527/foodmasters", "saqib", "saqib");
                        } 
                      catch (SQLException ex) {
                            JOptionPane.showMessageDialog(rootPane, "DB connection failed", "Connection failed ", HEIGHT);
                        }
          try{            
         ps = con.createStatement();
         ps.executeUpdate("Insert into saqib.users(name,email,password,mobile,role_id,validation) values ("+quotate(c.name)+","+quotate(c.email)+","+quotate(c.password)+","+quotate(c.mobile_no)+","+c.rol_id+","+0+")");
         JOptionPane.showMessageDialog(rootPane, "inserted", "done ", HEIGHT);      
            } 
          catch (SQLException ex) 
          {
            Logger.getLogger(sign_up.class.getName()).log(Level.SEVERE, null, ex);
    }                                        
             }
          else
           {
               if (flag==false)
               {
                  JOptionPane.showMessageDialog(rootPane, "email not valid", "bye", HEIGHT);
               }
               if(flag1==false)
               {
                   JOptionPane.showMessageDialog(rootPane, "mobile number not valid", "bye", HEIGHT);
               }
             
            }
          }
    }
   
      public String quotate(String content){
    
        return "'"+content+"'";
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sign_up.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new restaurant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration                   
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

